In [2]:
import pandas as pd
import sklearn as sk
import numpy as np
import matplotlib as plt
from sklearn.model_selection import train_test_split
from geopy.distance import geodesic
from pyproj import Geod
import seaborn as sns

In [3]:
data = pd.read_csv('NYC Taxi Project/test.csv')

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9914 entries, 0 to 9913
Data columns (total 7 columns):
key                  9914 non-null object
pickup_datetime      9914 non-null object
pickup_longitude     9914 non-null float64
pickup_latitude      9914 non-null float64
dropoff_longitude    9914 non-null float64
dropoff_latitude     9914 non-null float64
passenger_count      9914 non-null int64
dtypes: float64(4), int64(1), object(2)
memory usage: 542.2+ KB

In [5]:
train_data = pd.read_csv('NYC Taxi Project/train.csv')

In [13]:
#y = train_data.fare_amount
#X = train_data.drop()

In [ ]:
#Testing Train_Test_Split function on sample data

In [6]:
sample = train_data.head(10000)

In [7]:
y = sample.fare_amount #Label
X = sample.drop('fare_amount', axis=1)

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

In [9]:
train_data.info() #info function to figure out the missing data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55423856 entries, 0 to 55423855
Data columns (total 8 columns):
key                  object
fare_amount          float64
pickup_datetime      object
pickup_longitude     float64
pickup_latitude      float64
dropoff_longitude    float64
dropoff_latitude     float64
passenger_count      int64
dtypes: float64(5), int64(1), object(2)
memory usage: 3.3+ GB

In [10]:
sample.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
key                  10000 non-null object
fare_amount          10000 non-null float64
pickup_datetime      10000 non-null object
pickup_longitude     10000 non-null float64
pickup_latitude      10000 non-null float64
dropoff_longitude    10000 non-null float64
dropoff_latitude     10000 non-null float64
passenger_count      10000 non-null int64
dtypes: float64(5), int64(1), object(2)
memory usage: 625.1+ KB

In [11]:
sample.isnull().all() #Missing Data Check

key                  False
fare_amount          False
pickup_datetime      False
pickup_longitude     False
pickup_latitude      False
dropoff_longitude    False
dropoff_latitude     False
passenger_count      False
dtype: bool

In [ ]:
train_data.isnull().all() #Missing Data Check on all train data

In [ ]:
sample.head()

In [7]:
drop_off = (41.499498, -81.695391)
print(geodesic(newport_ri, cleveland_oh).miles)

NameError: name 'newport_ri' is not defined

In [86]:
pick_up = sample[['pickup_latitude', 'pickup_longitude']]
drop_off = sample[['dropoff_latitude', 'dropoff_longitude']]

In [94]:
#df_all['MILES'] = df_all.apply((lambda row: vincenty((row['LATITUDE'], 
#row['LONGITUDE']),(row['LAT'], row['LON'])).miles),axis=1)

#sample['distance'] = sample.apply(lambda row: vincenty((row['pickup_latitude'],row['pickup_longitude']),(row['dropoff_latitude'],row['dropoff_longitude'])).miles, axis=1)

#def calculate_distance(row):
#    return row['height'] * row['width']

#rectangles_df.apply(calculate_area, axis=1)

#rectangles_df['area'] = rectangles_df.apply(calculate_area, axis=1)
#rectangles_df

In [100]:
wgs84_geod = Geod(ellps='WGS84')

In [101]:
def Distance(lat1,lon1,lat2,lon2):
  az12,az21,dist = wgs84_geod.inv(lon1,lat1,lon2,lat2) #Yes, this order is correct
  return dist

In [102]:
sample['dist'] = Distance(sample['pickup_latitude'].tolist(),sample['pickup_longitude'].tolist(),sample['dropoff_latitude'].tolist(),sample['dropoff_longitude'].tolist())

c:\python3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [118]:
result = sample.loc[:, ['pickup_latitude']]
result1 = sample['pickup_latitude'].tolist()

In [120]:
result1 = sample.loc[:,['pickup_latitude']]
result2 = sample.loc[:,['pickup_longitude']]
result3 = sample.loc[:,['dropoff_latitude']]
result4 = sample.loc[:,['dropoff_latitude']]

In [122]:
sample['dist'] = Distance(result1,result2,result3,result4)

TypeError: input must be an array, list, tuple or scalar

In [123]:
sample

,key,fare_amount,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count,dist
0,2009-06-15 17:26:21.0000001,4.5,2009-06-15 17:26:21 UTC,-73.844311,40.721319,-73.841610,40.712278,1,8.832444e+06
1,2010-01-05 16:52:16.0000002,16.9,2010-01-05 16:52:16 UTC,-74.016048,40.711303,-73.979268,40.782004,1,8.842002e+06
2,2011-08-18 00:35:00.00000049,5.7,2011-08-18 00:35:00 UTC,-73.982738,40.761270,-73.991242,40.750562,2,8.836704e+06
3,2012-04-21 04:30:42.0000001,7.7,2012-04-21 04:30:42 UTC,-73.987130,40.733143,-73.991567,40.758092,1,8.839043e+06
4,2010-03-09 07:51:00.000000135,5.3,2010-03-09 07:51:00 UTC,-73.968095,40.768008,-73.956655,40.783762,1,8.834633e+06
5,2011-01-06 09:50:45.0000002,12.1,2011-01-06 09:50:45 UTC,-74.000964,40.731630,-73.972892,40.758233,1,8.839978e+06
6,2012-11-20 20:35:00.0000001,7.5,2012-11-20 20:35:00 UTC,-73.980002,40.751662,-73.973802,40.764842,1,8.837016e+06
7,2012-01-04 17:22:00.00000081,16.5,2012-01-04 17:22:00 UTC,-73.951300,40.774138,-73.990095,40.751048,1,8.833816e+06
8,2012-12-03 13:10:00.000000125,9.0,2012-12-03 13:10:00 UTC,-74.006462,40.726713,-73.993078,40.731628,1,8.841230e+06
9,2009-09-02 01:11:00.00000083,8.9,2009-09-02 01:11:00 UTC,-73.980658,40.733873,-73.991540,40.758138,2,8.838601e+06
10,2012-04-08 07:30:50.0000002,5.3,2012-04-08 07:30:50 UTC,-73.996335,40.737142,-73.980721,40.733559,1,8.839765e+06
11,2012-12-24 11:24:00.00000098,5.5,2012-12-24 11:24:00 UTC,0.000000,0.000000,0.000000,0.000000,3,0.000000e+00
12,2009-11-06 01:04:03.0000002,4.1,2009-11-06 01:04:03 UTC,-73.991601,40.744712,-73.983081,40.744682,2,8.838660e+06
13,2013-07-02 19:54:00.000000232,7.0,2013-07-02 19:54:00 UTC,-74.005360,40.728867,-74.008913,40.710907,1,8.841411e+06
14,2011-04-05 17:11:05.0000001,7.7,2011-04-05 17:11:05 UTC,-74.001821,40.737547,-73.998060,40.722788,2,8.840274e+06
15,2013-11-23 12:57:00.000000190,5.0,2013-11-23 12:57:00 UTC,0.000000,0.000000,0.000000,0.000000,1,0.000000e+00
16,2014-02-19 07:22:00.00000074,12.5,2014-02-19 07:22:00 UTC,-73.986430,40.760465,-73.988990,40.737075,1,8.837259e+06
17,2009-07-22 16:08:00.000000163,5.3,2009-07-22 16:08:00 UTC,-73.981060,40.737690,-73.994177,40.728412,1,8.838921e+06
18,2010-07-07 14:52:00.00000044,5.3,2010-07-07 14:52:00 UTC,-73.969505,40.784843,-73.958732,40.783357,1,8.833389e+06
19,2014-12-06 20:36:22.0000008,4.0,2014-12-06 20:36:22 UTC,-73.979815,40.751902,-73.979446,40.755481,1,8.837175e+06
20,2010-09-07 13:18:00.000000175,10.5,2010-09-07 13:18:00 UTC,-73.985382,40.747858,-73.978377,40.762070,1,8.837692e+06
21,2013-02-12 12:15:46.0000002,11.5,2013-02-12 12:15:46 UTC,-73.957954,40.779252,-73.961250,40.758787,1,8.833647e+06
22,2009-08-06 18:17:23.0000001,4.5,2009-08-06 18:17:23 UTC,-73.991707,40.770505,-73.985459,40.763671,1,8.836237e+06
23,2010-12-06 12:29:00.000000199,4.9,2010-12-06 12:29:00 UTC,-74.000632,40.747473,-73.986672,40.740577,1,8.839058e+06
24,2009-12-10 15:37:00.00000020,6.1,2009-12-10 15:37:00 UTC,-73.969622,40.756973,-73.981152,40.759712,1,8.836085e+06
25,2011-06-21 16:15:00.00000073,7.3,2011-06-21 16:15:00 UTC,-73.991875,40.754437,-73.977230,40.774323,3,8.837306e+06
26,2011-02-07 20:01:00.000000114,6.5,2011-02-07 20:01:00 UTC,0.000000,0.000000,0.000000,0.000000,1,0.000000e+00
27,2011-06-28 19:47:00.000000168,4.5,2011-06-28 19:47:00 UTC,-73.988893,40.760160,-73.986445,40.757857,3,8.837009e+06
28,2012-05-04 06:11:20.0000002,9.3,2012-05-04 06:11:20 UTC,-73.989258,40.690835,-74.004133,40.725690,1,8.843176e+06
29,2013-08-11 00:52:00.00000026,4.5,2013-08-11 00:52:00 UTC,-73.981020,40.737760,-73.980668,40.730497,2,8.838872e+06
...,...,...,...,...,...,...,...,...,...
9999970,2013-04-20 16:21:00.000000154,9.0,2013-04-20 16:21:00 UTC,-74.001970,40.709221,-73.991634,40.731094,3,8.842362e+06
9999971,2014-01-10 12:32:00.00000051,5.0,2014-01-10 12:32:00 UTC,-73.992987,40.743810,-73.986003,40.752247,2,8.838661e+06
9999972,2014-02-14 06:52:00.00000086,5.0,2014-02-14 06:52:00 UTC,-73.966297,40.761682,-73.954093,40.766973,5,8.835368e+06
9999973,2011-03-16 13:15:00.000000113,9.7,2011-03-16 13:15:00 UTC,-73.994168,40.751312,-73.995660,40.769080,1,8.837795e+06
9999974,2012-03-11 00:48:00.000000180,8.1,2012-03-11 00:48:00 UTC,-73.963702,40.774297,-73.989115,40.768212,1,8.834189e+06
9999975,2012-08-21 12:30:00.000000143,28.1,2012-08-21 12:30:00 UTC,-73.993312,40.735732,-73.873797,40.771472,5,8.838933e+06
9999976,2010-09-19 21:17:33.00000011,5.3,2010-09-19 21:17:33 UTC,-73.873007,40.774143,-73.943245,40.674908,2,8.830709e+06
9999977,2011-12-13 13:17:23.0000001,13.7,2011-12-13 13:17:23 UTC,-73.985187,40.744861,-74.005819,40.706397,1,8.839040e+06
9999978,2012-11-03 09:25:20.0000003,19.0,2012-11-03 09:25:20 UTC,-73.957305,40.774668,-73.940188,40.841365,1,8.832297e+06
9999979,2010-12-16 17:52:39.0000004,6.1,2010-12-16 17:52:39 UTC,-73.973791,40.784593,-73.960528,40.807607,1,8.833169e+06
9999980,2015-02-12 23:30:38.0000008,14.5,2015-02-12 23:30:38 UTC,-73.974197,40.761551,-73.963242,40.802128,1,8.835133e+06
9999981,2010-06-16 09:21:00.000000106,4.9,2010-06-16 09:21:00 UTC,-73.696362,40.632488,-73.703765,40.627288,1,8.832343e+06
9999982,2010-07-10 18:07:00.00000067,4.9,2010-07-10 18:07:00 UTC,-73.947290,40.791027,-73.953898,40.778013,2,8.831694e+06
9999983,2011-01-08 21:48:00.00000070,5.7,2011-01-08 21:48:00 UTC,-73.991167,40.750238,-73.980848,40.744720,1,8.838196e+06
9999984,2013-04-22 13:41:50.0000001,6.0,2013-04-22 13:41:50 UTC,-73.991281,40.755477,-73.983392,40.756923,1,8.837540e+06
9999985,2013-12-29 21:14:00.000000107,4.5,2013-12-29 21:14:00 UTC,-73.985622,40.756480,-73.989957,40.751437,1,8.837237e+06
9999986,2015-02-20 01:57:35.0000003,5.5,2015-02-20 01:57:35 UTC,-73.976280,40.751896,-73.978111,40.741833,2,8.837242e+06
9999987,2010-01-14 17:42:39.0000001,18.1,2010-01-14 17:42:39 UTC,-73.870846,40.773890,-73.953552,40.733910,1,8.829422e+06
9999988,2011-09-01 18:38:26.0000003,6.1,2011-09-01 18:38:26 UTC,-73.974985,40.755851,-73.976327,40.762358,4,8.836438e+06
9999989,2012-10-03 12:59:00.00000019,7.0,2012-10-03 12:59:00 UTC,-74.009206,40.724112,-74.004166,40.741382,1,8.841402e+06
9999990,2013-03-05 23:55:12.0000001,11.0,2013-03-05 23:55:12 UTC,-73.977005,40.758690,-73.982421,40.727640,2,8.837033e+06
9999991,2013-09-13 07:56:00.00000069,12.5,2013-09-13 07:56:00 UTC,-73.781852,40.644812,-73.779863,40.666525,1,8.835690e+06
9999992,2014-06-27 14:37:49.0000002,4.5,2014-06-27 14:37:49 UTC,-73.957567,40.779315,-73.951970,40.781583,2,8.833158e+06
9999993,2015-01-14 09:11:18.0000006,12.0,2015-01-14 09:11:18 UTC,-73.987755,40.738155,-73.972076,40.762775,1,8.838588e+06
9999994,2010-03-13 20:28:00.00000033,5.7,2010-03-13 20:28:00 UTC,-74.001518,40.730850,-73.991845,40.744305,2,8.840354e+06
9999995,2012-08-12 01:18:00.000000208,5.7,2012-08-12 01:18:00 UTC,-73.999464,40.728452,-73.993299,40.742100,2,8.840467e+06
9999996,2013-08-07 10:28:00.000000147,5.5,2013-08-07 10:28:00 UTC,-73.968467,40.759367,-73.964967,40.769027,1,8.835639e+06
9999997,2013-10-29 08:29:00.00000082,14.0,2013-10-29 08:29:00 UTC,-73.997952,40.733717,-73.973448,40.759122,5,8.839616e+06
9999998,2012-04-07 16:41:33.0000004,10.5,2012-04-07 16:41:33 UTC,-73.992700,40.752021,-73.964705,40.772849,1,8.837576e+06
9999999,2010-03-30 19:27:00.00000066,8.5,2010-03-30 19:27:00 UTC,-73.965390,40.768572,-73.998188,40.761073,1,8.834888e+06